/*
 * Generated by dtrace(1M).
 */

#ifndef	_BAR_H
#define	_BAR_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define BAR_STABILITY "___dtrace_stability$Bar$v1$1_1_0_1_1_0_1_1_0_1_1_0_5_5_5"

#define BAR_TYPEDEFS "___dtrace_typedefs$Bar$v2$776569726454797065"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	BAR_COUNT1(arg0) \
do { \
	__asm__ volatile(".reference " BAR_TYPEDEFS); \
	__dtrace_probe$Bar$count1$v1$776569726454797065(arg0); \
	__asm__ volatile(".reference " BAR_STABILITY); \
} while (0)
#define	BAR_COUNT1_ENABLED() \
	({ int _r = __dtrace_isenabled$Bar$count1$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$Bar$count1$v1$776569726454797065(weirdType);
extern int __dtrace_isenabled$Bar$count1$v1(void);

#else

#define	BAR_COUNT1(arg0) \
do { \
	} while (0)
#define	BAR_COUNT1_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _BAR_H */
