/*
 * Generated by dtrace(1M).
 */

#ifndef	_NUMBER_H
#define	_NUMBER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define NUMBER_STABILITY "___dtrace_stability$Number$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define NUMBER_TYPEDEFS "___dtrace_typedefs$Number$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	NUMBER_HIT(arg0) \
do { \
	__asm__ volatile(".reference " NUMBER_TYPEDEFS); \
	__dtrace_probe$Number$hit$v1$696e74(arg0); \
	__asm__ volatile(".reference " NUMBER_STABILITY); \
} while (0)
#define	NUMBER_HIT_ENABLED() \
	({ int _r = __dtrace_isenabled$Number$hit$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$Number$hit$v1$696e74(int);
extern int __dtrace_isenabled$Number$hit$v1(void);

#else

#define	NUMBER_HIT(arg0) \
do { \
	} while (0)
#define	NUMBER_HIT_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _NUMBER_H */
